import React, { createContext, useContext, useState, useCallback } from 'react';

// ─── Supported languages ──────────────────────────────────────────────────────
export const LANGUAGES = [
  { code: 'en', label: 'EN', fullLabel: 'English', flag: '🇬🇧' },
  { code: 'uz', label: "O'Z", fullLabel: "O'zbek", flag: '🇺🇿' },
  { code: 'ru', label: 'РУ', fullLabel: 'Русский', flag: '🇷🇺' },
];

// ─── All UI translations ──────────────────────────────────────────────────────
export const translations = {
  en: {
    // Announcement
    announcement: 'Complimentary shipping on orders over $150 — Worldwide',

    // Nav
    nav_towels: 'Towels',
    nav_robes: 'Robes',
    nav_bedding: 'Bedding',
    nav_luggage: 'Luggage',
    nav_all: 'All Products',
    nav_admin: 'Admin Dashboard',
    nav_signin: 'Sign In',
    nav_signout: 'Sign Out',
    nav_demo: 'Demo: admin@luxetextiles.com / admin123',

    // Search
    search_placeholder: 'Search for towels, robes, bedding, luggage…',

    // Header / Footer
    footer_newsletter_title: 'Stay in the thread.',
    footer_newsletter_sub: 'New arrivals, care tips, and members-only offers.',
    footer_subscribe: 'Subscribe',
    footer_rights: '© {year} LUXE Textiles. All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_cookies: 'Cookie Settings',
    footer_since: 'Crafting premium textile goods for the thoughtful home since 2010.',

    // Footer links
    footer_shop: 'Shop',
    footer_company: 'Company',
    footer_support: 'Support',
    footer_new_arrivals: 'New Arrivals',
    footer_about: 'About Us',
    footer_sustainability: 'Sustainability',
    footer_careers: 'Careers',
    footer_press: 'Press',
    footer_shipping: 'Shipping & Returns',
    footer_care: 'Care Instructions',
    footer_size: 'Size Guide',
    footer_contact: 'Contact Us',

    // Home page
    home_eyebrow: 'The Art of Everyday Luxury',
    home_hero_h1_1: 'Where Comfort',
    home_hero_h1_em: 'meets',
    home_hero_h1_2: 'Craft',
    home_hero_body: 'Curated premium textiles for the home. From 600-GSM Turkish cotton to 400-thread-count Egyptian sateen — everything your home deserves.',
    home_shop_all: 'Shop All Collections',
    home_explore_bedding: 'Explore Bedding',
    home_categories_eyebrow: 'Browse by Category',
    home_categories_h2: 'Every corner of your home, covered.',
    home_shop_now: 'Shop Now',
    home_featured_eyebrow: 'Hand-picked for you',
    home_featured_h2: 'Featured Pieces',
    home_view_all: 'View all',
    home_view_all_btn: 'View All Products',
    home_val_1_title: 'Premium Materials',
    home_val_1_body: 'Only long-staple cotton, linen, and certified sustainable fibres.',
    home_val_2_title: 'Artisan Crafted',
    home_val_2_body: 'Partnering with family mills across Turkey, Egypt, and Portugal.',
    home_val_3_title: 'Free Shipping',
    home_val_3_body: 'Complimentary worldwide shipping on all orders over $150.',
    home_val_4_title: '30-Day Returns',
    home_val_4_body: 'Not satisfied? Return unused items within 30 days.',
    home_cta_eyebrow: 'New Collection',
    home_cta_h2: 'The Sleep Edit is here.',
    home_cta_body: '400-thread-count Egyptian sateen and percale sheets. The finest sleep you\'ll ever have.',
    home_cta_btn: 'Discover Bedding',

    // Categories
    cat_towels: 'Towels',
    cat_robes: 'Robes',
    cat_bedding: 'Bedding',
    cat_suitcases: 'Luggage',
    cat_towels_sub: 'Turkish & Egyptian cotton',
    cat_robes_sub: 'Spa-grade luxury',
    cat_bedding_sub: 'Sleep in refinement',
    cat_suitcases_sub: 'Travel beautifully',

    // Shop page
    shop_collection: 'Collection',
    shop_results_for: 'Results for',
    shop_featured: 'Featured',
    shop_newest: 'Newest',
    shop_price_asc: 'Price: Low to High',
    shop_price_desc: 'Price: High to Low',
    shop_top_rated: 'Top Rated',
    shop_in_stock: 'In stock only',
    shop_results: '{n} results',
    shop_clear: 'Clear',
    shop_search: 'Search products…',
    shop_filters: 'Filters',
    shop_all: 'All',
    shop_no_products: 'No products found',
    shop_no_products_sub: "Try adjusting your search or filters to find what you're looking for.",

    // Product card
    card_featured: 'Featured',
    card_out_of_stock: 'Out of Stock',
    card_only_left: 'Only {n} left',
    card_quick_add: 'Quick Add',

    // Product detail
    detail_breadcrumb_home: 'Home',
    detail_breadcrumb_shop: 'Shop',
    detail_not_found: 'Product Not Found',
    detail_not_found_sub: 'This product may have been removed.',
    detail_back: 'Back to Shop',
    detail_color: 'Color',
    detail_size: 'Size',
    detail_quantity: 'Quantity',
    detail_add_cart: 'Add to Cart',
    detail_out_of_stock: 'Out of Stock',
    detail_free_shipping: 'Free Shipping',
    detail_free_shipping_sub: 'Orders over $150',
    detail_returns: '30-Day Returns',
    detail_returns_sub: 'Hassle-free',
    detail_authentic: 'Authentic',
    detail_authentic_sub: 'Certified materials',
    detail_related_eyebrow: 'You might also like',
    detail_related_h2: 'Related Products',
    detail_view_all: 'View all →',
    detail_select_color: 'Please select a color',
    detail_select_size: 'Please select a size',
    detail_added_cart: '"{name}" added to cart',

    // Cart
    cart_title: 'Your Cart',
    cart_empty_title: 'Your cart is empty',
    cart_empty_sub: "You haven't added anything yet. Explore our collections.",
    cart_continue: 'Continue Shopping',
    cart_clear: 'Clear all',
    cart_cleared: 'Cart cleared',
    cart_removed: '"{name}" removed from cart',
    cart_color: 'Color',
    cart_size: 'Size',
    cart_summary: 'Order Summary',
    cart_subtotal: 'Subtotal ({n} items)',
    cart_shipping: 'Shipping',
    cart_free_shipping: 'Free',
    cart_shipping_threshold: 'Add ${n} more for free shipping',
    cart_total: 'Total',
    cart_checkout: 'Proceed to Checkout',
    cart_back: '← Continue Shopping',

    // Login
    login_welcome: 'Welcome back',
    login_subtitle: 'Sign in to your account',
    login_demo_hint: 'Demo: admin@luxetextiles.com / admin123 or user@luxetextiles.com / user123',
    login_email: 'Email Address',
    login_password: 'Password',
    login_forgot: 'Forgot password?',
    login_submit: 'Sign In',
    login_submitting: 'Signing in…',
    login_no_account: "Don't have an account?",
    login_create: 'Create one',
    login_hero_eyebrow: 'LUXE Textiles',
    login_hero_h2: 'The luxury of home, delivered.',
    login_hero_body: 'Sign in to manage your orders, save your wishlist, and access exclusive member pricing.',
    login_err_email_required: 'Email is required',
    login_err_email_invalid: 'Enter a valid email',
    login_err_password_required: 'Password is required',
    login_err_password_short: 'Password must be at least 6 characters',
    login_success: 'Welcome back!',
    login_invalid: 'Invalid email or password.',

    // Admin
    admin_eyebrow: 'Admin',
    admin_title: 'Product Management',
    admin_reset: 'Reset Data',
    admin_add: 'Add Product',
    admin_total: 'Total Products',
    admin_inventory: 'Inventory Value',
    admin_low_stock: 'Low Stock',
    admin_out_stock: 'Out of Stock',
    admin_search: 'Search products…',
    admin_all: 'All',
    admin_col_image: 'Image',
    admin_col_product: 'Product',
    admin_col_category: 'Category',
    admin_col_price: 'Price',
    admin_col_stock: 'Stock',
    admin_col_rating: 'Rating',
    admin_col_actions: 'Actions',
    admin_no_products: 'No products match your filters.',
    admin_access_denied: 'Access Denied',
    admin_access_denied_sub: 'You need admin privileges to view this page.',
    admin_signin: 'Sign In as Admin',
    admin_view: 'View product page',
    admin_edit: 'Edit product',
    admin_delete: 'Delete product',
    admin_reset_success: 'Catalog reset to initial data',
    admin_delete_title: 'Delete Product',
    admin_delete_msg: 'Are you sure you want to permanently delete "{name}"? This action cannot be undone.',
    admin_delete_btn: 'Delete',
    admin_cancel: 'Cancel',
    admin_updated: '"{name}" updated successfully',
    admin_added: '"{name}" added to catalog',
    admin_deleted: '"{name}" deleted',
    admin_featured: 'Featured',

    // Product form
    form_add_title: 'Add New Product',
    form_edit_title: 'Edit Product',
    form_name: 'Product Name *',
    form_name_placeholder: 'e.g. Aegean Cloud Towel',
    form_category: 'Category *',
    form_price: 'Price ($) *',
    form_description: 'Description *',
    form_description_placeholder: 'Describe the product…',
    form_images: 'Image URLs (comma-separated)',
    form_images_placeholder: 'https://…, https://…',
    form_colors: 'Colors (comma-separated)',
    form_colors_placeholder: 'Ivory, Slate, Sage',
    form_sizes: 'Sizes (comma-separated)',
    form_sizes_placeholder: 'S, M, L, XL',
    form_stock: 'Stock *',
    form_rating: 'Rating (0–5)',
    form_reviews: 'Review Count',
    form_tags: 'Tags (comma-separated)',
    form_tags_placeholder: 'bestseller, turkish-cotton, quick-dry',
    form_featured: 'Mark as Featured',
    form_update: 'Update Product',
    form_add: 'Add Product',
    form_cancel: 'Cancel',
    form_err_name: 'Name is required',
    form_err_category: 'Category is required',
    form_err_price: 'Enter a valid price',
    form_err_desc: 'Description is required',
    form_err_stock: 'Enter valid stock (0+)',
    form_err_rating: 'Rating must be 0–5',

    // Not found
    notfound_title: 'Page Not Found',
    notfound_sub: "The page you're looking for doesn't exist or has been moved.",
    notfound_home: 'Go Home',
    notfound_shop: 'Browse Shop',

    // Confirm modal
    confirm_are_you_sure: 'Are you sure?',
    confirm_cannot_undo: 'This action cannot be undone.',
    confirm_confirm: 'Confirm',
    confirm_cancel: 'Cancel',

    // Toast
    toast_added_cart: '"{name}" added to cart',
  },

  uz: {
    announcement: "$150 dan ortiq buyurtmalarga bepul yetkazib berish — Dunyo bo'ylab",

    nav_towels: 'Sochiqlar',
    nav_robes: 'Xalatlar',
    nav_bedding: 'Yotoq to\'shagi',
    nav_luggage: 'Bagaj',
    nav_all: 'Barcha mahsulotlar',
    nav_admin: 'Admin paneli',
    nav_signin: 'Kirish',
    nav_signout: 'Chiqish',
    nav_demo: 'Demo: admin@luxetextiles.com / admin123',

    search_placeholder: 'Sochiq, xalat, yotoq to\'shagi, bagaj qidiring…',

    footer_newsletter_title: 'Yangilikdan boxabar bo\'ling.',
    footer_newsletter_sub: 'Yangi mahsulotlar, g\'amxo\'rlik maslahatlari va a\'zolar uchun takliflar.',
    footer_subscribe: 'Obuna bo\'lish',
    footer_rights: '© {year} LUXE Textiles. Barcha huquqlar himoyalangan.',
    footer_privacy: 'Maxfiylik siyosati',
    footer_terms: 'Foydalanish shartlari',
    footer_cookies: 'Cookie sozlamalari',
    footer_since: '2010 yildan beri uylar uchun premium to\'qimachilik mahsulotlari.',

    footer_shop: 'Do\'kon',
    footer_company: 'Kompaniya',
    footer_support: 'Yordam',
    footer_new_arrivals: 'Yangi kelganlar',
    footer_about: 'Biz haqimizda',
    footer_sustainability: 'Barqarorlik',
    footer_careers: 'Karyera',
    footer_press: 'Matbuot',
    footer_shipping: 'Yetkazib berish va qaytarish',
    footer_care: 'Parvarish ko\'rsatmalari',
    footer_size: 'O\'lcham jadvali',
    footer_contact: 'Biz bilan bog\'laning',

    home_eyebrow: 'Kundalik hashamatning san\'ati',
    home_hero_h1_1: 'Qulaylik',
    home_hero_h1_em: 'va',
    home_hero_h1_2: "Mahorat uchrashgan joy",
    home_hero_body: "Uy uchun tanlangan premium to'qimalar. 600 GSM turk paxtasidan 400 ipli misr sateni — uyingiz layiq bo'lgan hamma narsa.",
    home_shop_all: 'Barcha kollekciyani ko\'rish',
    home_explore_bedding: "Yotoq to'shagini ko'rish",
    home_categories_eyebrow: 'Kategoriya bo\'yicha ko\'rish',
    home_categories_h2: 'Uyingizning har bir burchagi uchun.',
    home_shop_now: 'Xarid qilish',
    home_featured_eyebrow: 'Siz uchun tanlangan',
    home_featured_h2: 'Tanlangan mahsulotlar',
    home_view_all: 'Hammasini ko\'rish',
    home_view_all_btn: 'Barcha mahsulotlar',
    home_val_1_title: 'Premium Materiallar',
    home_val_1_body: "Faqat uzun tolali paxta, zig'ir va sertifikatlangan barqaror tolalar.",
    home_val_2_title: 'Usta Ishlanma',
    home_val_2_body: "Turkiya, Misr va Portugaliyadagi oilaviy fabrikalarga tayanamiz.",
    home_val_3_title: 'Bepul Yetkazib Berish',
    home_val_3_body: "$150 dan ortiq barcha buyurtmalar uchun dunyo bo'ylab bepul.",
    home_val_4_title: '30 Kunlik Qaytarish',
    home_val_4_body: "Mamnun emasmi? Ishlatilmagan mahsulotlarni 30 kun ichida qaytaring.",
    home_cta_eyebrow: 'Yangi Kolleksiya',
    home_cta_h2: "Uyqu to'shagi muharririyati keldi.",
    home_cta_body: "400 ipli misr sateni va perskal choyshablar. Umringizda ko'rgan eng go'zal uyqu.",
    home_cta_btn: "Yotoq to'shagini ko'rish",

    cat_towels: 'Sochiqlar',
    cat_robes: 'Xalatlar',
    cat_bedding: "Yotoq to'shagi",
    cat_suitcases: 'Bagaj',
    cat_towels_sub: "Turk va misr paxtasi",
    cat_robes_sub: 'Spa darajasidagi hashamat',
    cat_bedding_sub: 'Nafis uyquda',
    cat_suitcases_sub: 'Chiroyli sayohat qiling',

    shop_collection: 'Kolleksiya',
    shop_results_for: "Qidiruv natijalari",
    shop_featured: 'Tanlangan',
    shop_newest: 'Eng yangi',
    shop_price_asc: "Narx: arzondan qimmatga",
    shop_price_desc: "Narx: qimmatdan arzonga",
    shop_top_rated: 'Yuqori baholangan',
    shop_in_stock: 'Faqat omborda borlar',
    shop_results: '{n} natija',
    shop_clear: 'Tozalash',
    shop_search: 'Mahsulot qidirish…',
    shop_filters: 'Filtrlar',
    shop_all: 'Barchasi',
    shop_no_products: 'Mahsulot topilmadi',
    shop_no_products_sub: "Qidiruv yoki filtrlarni o'zgartirib ko'ring.",

    card_featured: 'Tanlangan',
    card_out_of_stock: 'Tugagan',
    card_only_left: 'Faqat {n} ta qoldi',
    card_quick_add: 'Tez qo\'shish',

    detail_breadcrumb_home: 'Bosh sahifa',
    detail_breadcrumb_shop: "Do'kon",
    detail_not_found: 'Mahsulot topilmadi',
    detail_not_found_sub: "Bu mahsulot o'chirilgan bo'lishi mumkin.",
    detail_back: "Do'konga qaytish",
    detail_color: 'Rang',
    detail_size: "O'lcham",
    detail_quantity: 'Miqdor',
    detail_add_cart: 'Savatga qo\'shish',
    detail_out_of_stock: 'Tugagan',
    detail_free_shipping: 'Bepul Yetkazish',
    detail_free_shipping_sub: "$150 dan ortiq buyurtmalarga",
    detail_returns: '30 Kunlik Qaytarish',
    detail_returns_sub: 'Muammosiz',
    detail_authentic: 'Original',
    detail_authentic_sub: 'Sertifikatlangan materiallar',
    detail_related_eyebrow: 'Sizga ham yoqishi mumkin',
    detail_related_h2: 'O\'xshash mahsulotlar',
    detail_view_all: 'Hammasini ko\'rish →',
    detail_select_color: 'Rang tanlang',
    detail_select_size: "O'lcham tanlang",
    detail_added_cart: '"{name}" savatga qo\'shildi',

    cart_title: 'Savatcha',
    cart_empty_title: 'Savatingiz bo\'sh',
    cart_empty_sub: "Hali hech narsa qo'shmagansiz. Kollekciyalarimizni ko'ring.",
    cart_continue: 'Xaridni davom ettirish',
    cart_clear: 'Hammasini tozalash',
    cart_cleared: 'Savatcha tozalandi',
    cart_removed: '"{name}" savatdan olib tashlandi',
    cart_color: 'Rang',
    cart_size: "O'lcham",
    cart_summary: 'Buyurtma xulosasi',
    cart_subtotal: "Jami ({n} ta mahsulot)",
    cart_shipping: 'Yetkazib berish',
    cart_free_shipping: 'Bepul',
    cart_shipping_threshold: "Bepul yetkazib berish uchun yana ${n} qo'shing",
    cart_total: 'Jami',
    cart_checkout: 'Buyurtmani rasmiylashtirish',
    cart_back: '← Xaridni davom ettirish',

    login_welcome: 'Xush kelibsiz',
    login_subtitle: 'Hisobingizga kirish',
    login_demo_hint: 'Demo: admin@luxetextiles.com / admin123 yoki user@luxetextiles.com / user123',
    login_email: 'Elektron pochta',
    login_password: 'Parol',
    login_forgot: 'Parolni unutdingizmi?',
    login_submit: 'Kirish',
    login_submitting: 'Kirilmoqda…',
    login_no_account: 'Hisobingiz yo\'qmi?',
    login_create: 'Yarating',
    login_hero_eyebrow: 'LUXE Textiles',
    login_hero_h2: 'Uyning hashamati, yetkazib beriladi.',
    login_hero_body: 'Buyurtmalaringizni boshqarish, istaklar ro\'yxatini saqlash va eksklyuziv narxlardan foydalanish uchun kiring.',
    login_err_email_required: 'Elektron pochta kiritilishi shart',
    login_err_email_invalid: "To'g'ri elektron pochta kiriting",
    login_err_password_required: 'Parol kiritilishi shart',
    login_err_password_short: "Parol kamida 6 ta belgi bo'lishi kerak",
    login_success: 'Xush kelibsiz!',
    login_invalid: "Elektron pochta yoki parol noto'g'ri.",

    admin_eyebrow: 'Admin',
    admin_title: 'Mahsulotlarni boshqarish',
    admin_reset: 'Ma\'lumotni tiklash',
    admin_add: 'Mahsulot qo\'shish',
    admin_total: 'Jami mahsulotlar',
    admin_inventory: 'Ombor qiymati',
    admin_low_stock: 'Kam qolgan',
    admin_out_stock: 'Tugagan',
    admin_search: 'Mahsulot qidirish…',
    admin_all: 'Barchasi',
    admin_col_image: 'Rasm',
    admin_col_product: 'Mahsulot',
    admin_col_category: 'Kategoriya',
    admin_col_price: 'Narx',
    admin_col_stock: 'Zaxira',
    admin_col_rating: 'Baho',
    admin_col_actions: 'Amallar',
    admin_no_products: "Filtrga mos mahsulot topilmadi.",
    admin_access_denied: "Kirish taqiqlangan",
    admin_access_denied_sub: "Bu sahifani ko'rish uchun admin huquqi kerak.",
    admin_signin: 'Admin sifatida kirish',
    admin_view: 'Mahsulot sahifasini ko\'rish',
    admin_edit: 'Tahrirlash',
    admin_delete: "O'chirish",
    admin_reset_success: "Katalog boshlang'ich ma'lumotlarga tiklandi",
    admin_delete_title: "Mahsulotni o'chirish",
    admin_delete_msg: '"{name}" ni doimiy ravishda o\'chirmoqchimisiz? Bu amalni bekor qilib bo\'lmaydi.',
    admin_delete_btn: "O'chirish",
    admin_cancel: 'Bekor qilish',
    admin_updated: '"{name}" muvaffaqiyatli yangilandi',
    admin_added: '"{name}" katalogga qo\'shildi',
    admin_deleted: '"{name}" o\'chirildi',
    admin_featured: 'Tanlangan',

    form_add_title: 'Yangi mahsulot qo\'shish',
    form_edit_title: 'Mahsulotni tahrirlash',
    form_name: 'Mahsulot nomi *',
    form_name_placeholder: 'masalan: Aegean Cloud Sochiq',
    form_category: 'Kategoriya *',
    form_price: 'Narx ($) *',
    form_description: 'Tavsif *',
    form_description_placeholder: 'Mahsulotni tasvirlang…',
    form_images: 'Rasm URL\'lari (vergul bilan ajrating)',
    form_images_placeholder: 'https://…, https://…',
    form_colors: 'Ranglar (vergul bilan ajrating)',
    form_colors_placeholder: 'Fil suyagi, Ko\'k, Yashil',
    form_sizes: "O'lchamlar (vergul bilan ajrating)",
    form_sizes_placeholder: 'S, M, L, XL',
    form_stock: 'Zaxira *',
    form_rating: 'Baho (0–5)',
    form_reviews: 'Sharhlar soni',
    form_tags: 'Teglar (vergul bilan ajrating)',
    form_tags_placeholder: 'bestseller, turk-paxtasi, tez-quriydigan',
    form_featured: "Tanlangan sifatida belgilash",
    form_update: 'Mahsulotni yangilash',
    form_add: 'Mahsulot qo\'shish',
    form_cancel: 'Bekor qilish',
    form_err_name: 'Nom kiritilishi shart',
    form_err_category: 'Kategoriya tanlanishi shart',
    form_err_price: "To'g'ri narx kiriting",
    form_err_desc: 'Tavsif kiritilishi shart',
    form_err_stock: "To'g'ri zaxira kiriting (0+)",
    form_err_rating: 'Baho 0 dan 5 gacha bo\'lishi kerak',

    notfound_title: 'Sahifa topilmadi',
    notfound_sub: "Siz izlayotgan sahifa mavjud emas yoki ko'chirilgan.",
    notfound_home: 'Bosh sahifaga',
    notfound_shop: "Do'konga",

    confirm_are_you_sure: 'Ishonchingiz komilmi?',
    confirm_cannot_undo: 'Bu amalni bekor qilib bo\'lmaydi.',
    confirm_confirm: 'Tasdiqlash',
    confirm_cancel: 'Bekor qilish',

    toast_added_cart: '"{name}" savatga qo\'shildi',
  },

  ru: {
    announcement: 'Бесплатная доставка при заказе от $150 — по всему миру',

    nav_towels: 'Полотенца',
    nav_robes: 'Халаты',
    nav_bedding: 'Постельное бельё',
    nav_luggage: 'Багаж',
    nav_all: 'Все товары',
    nav_admin: 'Панель администратора',
    nav_signin: 'Войти',
    nav_signout: 'Выйти',
    nav_demo: 'Демо: admin@luxetextiles.com / admin123',

    search_placeholder: 'Поиск полотенец, халатов, постельного белья, багажа…',

    footer_newsletter_title: 'Будьте в курсе.',
    footer_newsletter_sub: 'Новинки, советы по уходу и эксклюзивные предложения для участников.',
    footer_subscribe: 'Подписаться',
    footer_rights: '© {year} LUXE Textiles. Все права защищены.',
    footer_privacy: 'Политика конфиденциальности',
    footer_terms: 'Условия использования',
    footer_cookies: 'Настройки cookies',
    footer_since: 'Создаём премиальные текстильные изделия для дома с 2010 года.',

    footer_shop: 'Магазин',
    footer_company: 'Компания',
    footer_support: 'Поддержка',
    footer_new_arrivals: 'Новинки',
    footer_about: 'О нас',
    footer_sustainability: 'Устойчивость',
    footer_careers: 'Карьера',
    footer_press: 'Пресса',
    footer_shipping: 'Доставка и возврат',
    footer_care: 'Инструкции по уходу',
    footer_size: 'Таблица размеров',
    footer_contact: 'Свяжитесь с нами',

    home_eyebrow: 'Искусство повседневной роскоши',
    home_hero_h1_1: 'Там, где комфорт',
    home_hero_h1_em: 'встречает',
    home_hero_h1_2: 'мастерство',
    home_hero_body: 'Отборный премиальный текстиль для дома. От 600-GSM турецкого хлопка до 400-нитевого египетского сатина — всё, чего заслуживает ваш дом.',
    home_shop_all: 'Смотреть все коллекции',
    home_explore_bedding: 'Посмотреть постельное бельё',
    home_categories_eyebrow: 'Просмотр по категориям',
    home_categories_h2: 'Для каждого уголка вашего дома.',
    home_shop_now: 'В магазин',
    home_featured_eyebrow: 'Специально для вас',
    home_featured_h2: 'Избранные товары',
    home_view_all: 'Смотреть всё',
    home_view_all_btn: 'Все товары',
    home_val_1_title: 'Премиальные материалы',
    home_val_1_body: 'Только длинноволокнистый хлопок, лён и сертифицированные экологичные волокна.',
    home_val_2_title: 'Ручная работа',
    home_val_2_body: 'Сотрудничество с семейными фабриками в Турции, Египте и Португалии.',
    home_val_3_title: 'Бесплатная доставка',
    home_val_3_body: 'Бесплатная доставка по всему миру при заказе от $150.',
    home_val_4_title: 'Возврат за 30 дней',
    home_val_4_body: 'Не понравилось? Верните неиспользованный товар в течение 30 дней.',
    home_cta_eyebrow: 'Новая коллекция',
    home_cta_h2: 'Sleep Edit уже здесь.',
    home_cta_body: 'Простыни из 400-нитевого египетского сатина и перкаля. Лучший сон в вашей жизни.',
    home_cta_btn: 'Посмотреть постельное бельё',

    cat_towels: 'Полотенца',
    cat_robes: 'Халаты',
    cat_bedding: 'Постельное бельё',
    cat_suitcases: 'Багаж',
    cat_towels_sub: 'Турецкий и египетский хлопок',
    cat_robes_sub: 'Роскошь уровня спа',
    cat_bedding_sub: 'Спать в изысканности',
    cat_suitcases_sub: 'Путешествуйте красиво',

    shop_collection: 'Коллекция',
    shop_results_for: 'Результаты для',
    shop_featured: 'Рекомендуемые',
    shop_newest: 'Новинки',
    shop_price_asc: 'Цена: по возрастанию',
    shop_price_desc: 'Цена: по убыванию',
    shop_top_rated: 'Высокий рейтинг',
    shop_in_stock: 'Только в наличии',
    shop_results: '{n} результатов',
    shop_clear: 'Сбросить',
    shop_search: 'Поиск товаров…',
    shop_filters: 'Фильтры',
    shop_all: 'Все',
    shop_no_products: 'Товары не найдены',
    shop_no_products_sub: 'Попробуйте изменить поиск или фильтры.',

    card_featured: 'Рекомендуемый',
    card_out_of_stock: 'Нет в наличии',
    card_only_left: 'Осталось только {n}',
    card_quick_add: 'Быстро добавить',

    detail_breadcrumb_home: 'Главная',
    detail_breadcrumb_shop: 'Магазин',
    detail_not_found: 'Товар не найден',
    detail_not_found_sub: 'Возможно, этот товар был удалён.',
    detail_back: 'Вернуться в магазин',
    detail_color: 'Цвет',
    detail_size: 'Размер',
    detail_quantity: 'Количество',
    detail_add_cart: 'Добавить в корзину',
    detail_out_of_stock: 'Нет в наличии',
    detail_free_shipping: 'Бесплатная доставка',
    detail_free_shipping_sub: 'При заказе от $150',
    detail_returns: 'Возврат за 30 дней',
    detail_returns_sub: 'Без лишних хлопот',
    detail_authentic: 'Оригинальность',
    detail_authentic_sub: 'Сертифицированные материалы',
    detail_related_eyebrow: 'Вам также может понравиться',
    detail_related_h2: 'Похожие товары',
    detail_view_all: 'Смотреть всё →',
    detail_select_color: 'Выберите цвет',
    detail_select_size: 'Выберите размер',
    detail_added_cart: '"{name}" добавлен в корзину',

    cart_title: 'Корзина',
    cart_empty_title: 'Ваша корзина пуста',
    cart_empty_sub: 'Вы ещё ничего не добавили. Изучите наши коллекции.',
    cart_continue: 'Продолжить покупки',
    cart_clear: 'Очистить всё',
    cart_cleared: 'Корзина очищена',
    cart_removed: '"{name}" удалён из корзины',
    cart_color: 'Цвет',
    cart_size: 'Размер',
    cart_summary: 'Итог заказа',
    cart_subtotal: 'Подытог ({n} товара)',
    cart_shipping: 'Доставка',
    cart_free_shipping: 'Бесплатно',
    cart_shipping_threshold: 'Добавьте ещё ${n} для бесплатной доставки',
    cart_total: 'Итого',
    cart_checkout: 'Оформить заказ',
    cart_back: '← Продолжить покупки',

    login_welcome: 'С возвращением',
    login_subtitle: 'Войдите в свой аккаунт',
    login_demo_hint: 'Демо: admin@luxetextiles.com / admin123 или user@luxetextiles.com / user123',
    login_email: 'Электронная почта',
    login_password: 'Пароль',
    login_forgot: 'Забыли пароль?',
    login_submit: 'Войти',
    login_submitting: 'Вход…',
    login_no_account: 'Нет аккаунта?',
    login_create: 'Создать',
    login_hero_eyebrow: 'LUXE Textiles',
    login_hero_h2: 'Роскошь дома — доставлена.',
    login_hero_body: 'Войдите, чтобы управлять заказами, сохранять список желаний и получать эксклюзивные цены.',
    login_err_email_required: 'Введите электронную почту',
    login_err_email_invalid: 'Введите корректный адрес',
    login_err_password_required: 'Введите пароль',
    login_err_password_short: 'Пароль должен быть не менее 6 символов',
    login_success: 'С возвращением!',
    login_invalid: 'Неверный адрес электронной почты или пароль.',

    admin_eyebrow: 'Администратор',
    admin_title: 'Управление товарами',
    admin_reset: 'Сбросить данные',
    admin_add: 'Добавить товар',
    admin_total: 'Всего товаров',
    admin_inventory: 'Стоимость склада',
    admin_low_stock: 'Мало на складе',
    admin_out_stock: 'Нет в наличии',
    admin_search: 'Поиск товаров…',
    admin_all: 'Все',
    admin_col_image: 'Фото',
    admin_col_product: 'Товар',
    admin_col_category: 'Категория',
    admin_col_price: 'Цена',
    admin_col_stock: 'Склад',
    admin_col_rating: 'Рейтинг',
    admin_col_actions: 'Действия',
    admin_no_products: 'Нет товаров, соответствующих фильтрам.',
    admin_access_denied: 'Доступ запрещён',
    admin_access_denied_sub: 'Для просмотра этой страницы нужны права администратора.',
    admin_signin: 'Войти как администратор',
    admin_view: 'Просмотреть страницу товара',
    admin_edit: 'Редактировать',
    admin_delete: 'Удалить',
    admin_reset_success: 'Каталог сброшен до начальных данных',
    admin_delete_title: 'Удалить товар',
    admin_delete_msg: 'Вы уверены, что хотите удалить "{name}"? Это действие нельзя отменить.',
    admin_delete_btn: 'Удалить',
    admin_cancel: 'Отмена',
    admin_updated: '"{name}" успешно обновлён',
    admin_added: '"{name}" добавлен в каталог',
    admin_deleted: '"{name}" удалён',
    admin_featured: 'Рекомендуемый',

    form_add_title: 'Добавить новый товар',
    form_edit_title: 'Редактировать товар',
    form_name: 'Название товара *',
    form_name_placeholder: 'напр. Полотенце Aegean Cloud',
    form_category: 'Категория *',
    form_price: 'Цена ($) *',
    form_description: 'Описание *',
    form_description_placeholder: 'Опишите товар…',
    form_images: 'URL изображений (через запятую)',
    form_images_placeholder: 'https://…, https://…',
    form_colors: 'Цвета (через запятую)',
    form_colors_placeholder: 'Слоновая кость, Серый, Зелёный',
    form_sizes: 'Размеры (через запятую)',
    form_sizes_placeholder: 'S, M, L, XL',
    form_stock: 'Склад *',
    form_rating: 'Рейтинг (0–5)',
    form_reviews: 'Количество отзывов',
    form_tags: 'Теги (через запятую)',
    form_tags_placeholder: 'бестселлер, турецкий-хлопок, быстросохнущий',
    form_featured: 'Отметить как рекомендуемый',
    form_update: 'Обновить товар',
    form_add: 'Добавить товар',
    form_cancel: 'Отмена',
    form_err_name: 'Название обязательно',
    form_err_category: 'Категория обязательна',
    form_err_price: 'Введите корректную цену',
    form_err_desc: 'Описание обязательно',
    form_err_stock: 'Введите корректное количество (0+)',
    form_err_rating: 'Рейтинг должен быть от 0 до 5',

    notfound_title: 'Страница не найдена',
    notfound_sub: 'Страница, которую вы ищете, не существует или была перемещена.',
    notfound_home: 'На главную',
    notfound_shop: 'В магазин',

    confirm_are_you_sure: 'Вы уверены?',
    confirm_cannot_undo: 'Это действие нельзя отменить.',
    confirm_confirm: 'Подтвердить',
    confirm_cancel: 'Отмена',

    toast_added_cart: '"{name}" добавлен в корзину',
  },
};

// ─── Context ──────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

const STORAGE_KEY = 'luxe_textiles_language';

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved && translations[saved]) return saved;
    } catch { /* ignore */ }
    return 'en';
  });

  const setLang = useCallback((code) => {
    if (!translations[code]) return;
    localStorage.setItem(STORAGE_KEY, code);
    setLangState(code);
  }, []);

  /**
   * t('key') → translated string
   * t('key', { name: 'X', n: 3 }) → string with {name} and {n} replaced
   */
  const t = useCallback((key, vars = {}) => {
    const dict = translations[lang] ?? translations.en;
    let str = dict[key] ?? translations.en[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replaceAll(`{${k}}`, v);
    });
    return str;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}

// ─── Checkout translations patch (appended) ───────────────────────────────────
// These are injected into the existing translations object at runtime
const checkoutKeys = {
  en: {
    checkout_title: 'Checkout',
    checkout_back: '← Back to Cart',
    checkout_contact: 'Contact Information',
    checkout_fullname: 'Full Name *',
    checkout_fullname_ph: 'John Smith',
    checkout_phone: 'Phone Number *',
    checkout_phone_ph: '+998 90 123 45 67',
    checkout_delivery: 'Delivery Method',
    checkout_home_delivery: 'Home Delivery',
    checkout_pickup: 'Store Pickup',
    checkout_address: 'Delivery Address *',
    checkout_address_ph: 'Street, house number, apartment',
    checkout_city: 'City *',
    checkout_city_ph: 'Tashkent',
    checkout_comment: 'Order Comment (optional)',
    checkout_comment_ph: 'Any notes about your order…',
    checkout_payment: 'Payment Method',
    checkout_cash: 'Cash on Delivery',
    checkout_card: 'Bank Card',
    checkout_summary: 'Order Summary',
    checkout_items: '{n} items',
    checkout_shipping_label: 'Shipping',
    checkout_free: 'Free',
    checkout_total: 'Total',
    checkout_submit: 'Place Order via Telegram',
    checkout_submitting: 'Sending order…',
    checkout_success_title: 'Order Placed! 🎉',
    checkout_success_sub: 'Your order #{num} has been sent to {username} on Telegram. We will contact you shortly at {phone}.',
    checkout_success_btn: 'Continue Shopping',
    checkout_also_telegram: 'You can also message us directly:',
    checkout_open_telegram: 'Open Telegram Chat',
    checkout_err_name: 'Full name is required',
    checkout_err_phone: 'Enter a valid phone number',
    checkout_err_address: 'Address is required for home delivery',
    checkout_err_city: 'City is required',
    checkout_err_send: 'Failed to send order. Please try again or contact us directly.',
  },
  uz: {
    checkout_title: 'Buyurtmani rasmiylashtirish',
    checkout_back: '← Savatga qaytish',
    checkout_contact: 'Aloqa ma\'lumotlari',
    checkout_fullname: 'To\'liq ism *',
    checkout_fullname_ph: 'Malika Muhiddinova',
    checkout_phone: 'Telefon raqami *',
    checkout_phone_ph: '+998 90 123 45 67',
    checkout_delivery: 'Yetkazib berish usuli',
    checkout_home_delivery: 'Uyga yetkazib berish',
    checkout_pickup: 'Do\'kondan olish',
    checkout_address: 'Yetkazib berish manzili *',
    checkout_address_ph: 'Ko\'cha, uy raqami, xonadon',
    checkout_city: 'Shahar *',
    checkout_city_ph: 'Toshkent',
    checkout_comment: 'Buyurtmaga izoh (ixtiyoriy)',
    checkout_comment_ph: 'Buyurtmangiz haqida qo\'shimcha ma\'lumot…',
    checkout_payment: 'To\'lov usuli',
    checkout_cash: 'Naqd pul (yetkazganda)',
    checkout_card: 'Bank kartasi',
    checkout_summary: 'Buyurtma xulosasi',
    checkout_items: '{n} ta mahsulot',
    checkout_shipping_label: 'Yetkazib berish',
    checkout_free: 'Bepul',
    checkout_total: 'Jami',
    checkout_submit: 'Telegram orqali buyurtma berish',
    checkout_submitting: 'Buyurtma yuborilmoqda…',
    checkout_success_title: 'Buyurtma qabul qilindi! 🎉',
    checkout_success_sub: '#{num} raqamli buyurtmangiz Telegram orqali {username} ga yuborildi. Tez orada {phone} raqamiga murojaat qilamiz.',
    checkout_success_btn: 'Xaridni davom ettirish',
    checkout_also_telegram: 'Telegram orqali ham murojaat qilishingiz mumkin:',
    checkout_open_telegram: 'Telegramda ochish',
    checkout_err_name: 'To\'liq ism kiritilishi shart',
    checkout_err_phone: 'To\'g\'ri telefon raqami kiriting',
    checkout_err_address: 'Uyga yetkazish uchun manzil shart',
    checkout_err_city: 'Shahar kiritilishi shart',
    checkout_err_send: 'Buyurtma yuborishda xatolik. Qayta urinib ko\'ring yoki bizga to\'g\'ridan-to\'g\'ri murojaat qiling.',
  },
  ru: {
    checkout_title: 'Оформление заказа',
    checkout_back: '← Вернуться в корзину',
    checkout_contact: 'Контактная информация',
    checkout_fullname: 'Полное имя *',
    checkout_fullname_ph: 'Иван Иванов',
    checkout_phone: 'Номер телефона *',
    checkout_phone_ph: '+998 90 123 45 67',
    checkout_delivery: 'Способ доставки',
    checkout_home_delivery: 'Доставка на дом',
    checkout_pickup: 'Самовывоз',
    checkout_address: 'Адрес доставки *',
    checkout_address_ph: 'Улица, номер дома, квартира',
    checkout_city: 'Город *',
    checkout_city_ph: 'Ташкент',
    checkout_comment: 'Комментарий к заказу (необязательно)',
    checkout_comment_ph: 'Дополнительная информация о заказе…',
    checkout_payment: 'Способ оплаты',
    checkout_cash: 'Наличные при доставке',
    checkout_card: 'Банковская карта',
    checkout_summary: 'Итог заказа',
    checkout_items: '{n} товаров',
    checkout_shipping_label: 'Доставка',
    checkout_free: 'Бесплатно',
    checkout_total: 'Итого',
    checkout_submit: 'Оформить заказ через Telegram',
    checkout_submitting: 'Отправка заказа…',
    checkout_success_title: 'Заказ оформлен! 🎉',
    checkout_success_sub: 'Ваш заказ #{num} отправлен в Telegram на {username}. Мы свяжемся с вами по номеру {phone} в ближайшее время.',
    checkout_success_btn: 'Продолжить покупки',
    checkout_also_telegram: 'Также можете написать нам напрямую:',
    checkout_open_telegram: 'Открыть Telegram чат',
    checkout_err_name: 'Введите полное имя',
    checkout_err_phone: 'Введите корректный номер телефона',
    checkout_err_address: 'Адрес обязателен для доставки на дом',
    checkout_err_city: 'Укажите город',
    checkout_err_send: 'Не удалось отправить заказ. Попробуйте ещё раз или свяжитесь с нами напрямую.',
  },
};

// Merge checkout keys into main translations
Object.keys(checkoutKeys).forEach(lang => {
  if (translations[lang]) {
    Object.assign(translations[lang], checkoutKeys[lang]);
  }
});
